### PR TITLE
Add CODE_OF_CONDUCT.md and CONTRIBUTING.md files

### LINKED ISSUE #38: [FEATURE] It might be a good idea to add a CONTRIBUTION file and a CODE_OF_CONDUCT
**Is your feature request related to a problem? Please describe.**
I'd like to contribute with the code of `dblab`, but I don't know very well `golang`

**Describe the solution you'd like**
Maybe could be a good idea to add a `CONTRIBUTING` file for new contributors to get some context of the project and for the environment setup, also could be a good idea to add a `CODE_OF_CONDUCT` to the repo, for the interaction between developers

**Describe alternatives you've considered**
I tried to run the code after I cloned, but I got an error `Error: empty values required to open a session in database`, 
I'm using `Goland`, then I noticed that I'm running the app without parameters so when I added `--help`, the error disappear

### PR DESCRIPTION
**Pull request by israteneda**
# Pull Request Template

## Description

Add `CODE_OF_CONDUCT.md` and `CONTRIBUTING.md` files

Fixes #38 

## Type of change

Please delete options that are not relevant.

- [x] This change requires a documentation update

## Checklist:

- [x] I have made corresponding changes to the documentation
- [x] I have checked my code and corrected any misspellings

### CODE REVIEW

**Comment by israteneda** [comment]
hey @danvergara could you review the files, and check if I need to add something previous to move the PR to `Ready for review`

**Comment by danvergara** [comment]
@israteneda Of course I can. Thanks a lot for this contribution. Let me take a look a it.

**Comment by danvergara** [comment]
@israteneda Looks good overall. There's something that I'd like to add, if you take a look at the commit history you would notice that all the commit messages follow a standard which is [conventional commit](https://www.conventionalcommits.org/en/v1.0.0/). I use a cli tool called [Commitizen](https://github.com/commitizen-tools/commitizen) to build the commit messages. Can you add that standard to the contribution guide and suggest Commitizen as a tool?

**Comment by israteneda** [comment]
sure! @danvergara I'll add the conventional commit standard in the guide in the next days

**Comment by israteneda** [comment]
@danvergara I updated the CONTRIBUTING file

**Comment by danvergara** [comment]
Thanks @israteneda for this great contribution. Once the checks pass, I'll approve.

**Pull request merged**
